---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install Nginx
      apt: 
       name: nginx
       state: present

    - name: Ensure Nginx is enabled and started
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Install Java
      apt:
        name: default-jdk
        state: present