---
- hosts: all
  become: yes
  tasks:
    - name: Install Java
      apt:
        name: default-jdk
        state: present

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Start and enable Tomcat service
      systemd:
        name: tomcat9
        state: started
        enabled: yes
